name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html selenium webdriver-manager

      # 4. Run tests (headless Chrome)
      - name: Run pytest with HTML report
        run: pytest --html=report.html --self-contained-html

      # 5. Upload HTML report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: report.html
